language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Req7znLTYwWbkbo9HQlAmaTUN0ZWFc7rFmivWiqoDrNABEFtlvFUMP4TXX9tRB/Hi3USmIDXGjwlJan84PCndF/uyWGO0MfvIhitcbp8WVDX8SDy1sZ1VOfAluNVt4rCbVMMK5EdXtdhJmIM4tMYWNnQGjeSehZS/Nt5VberRtx8ChUTgHD6H7O/t4KTWsDWqrGJfrfNY8JqWmKU1E752vAyar76dmj35Ju0z/KaFr5/zulnO/iEFdpwI7NzLyN/4RYjEEHrl3jzt+yOnQ0h6ztonviihUfibbPLLJT6IKXUiMIFxyYcwQaEVAv9XQshPF2zJwrx72EltOAAHA1pKhOgTYDijCsSodYW40yfhOgZcoo+R5IyUZJkNc4N5EGja07aBeSczxi39WR8gppUZyPcmvtZsiLQsjX63k8iIh9XiZKZlsQj5muVTshqzdYWA3o+m+pkKlktR78NLbT/ewyyBfW9GlfmN0g2/tAg1T7TOvi5eMQIi8ShCN8xdMpQwYZVMV3hIyKqdpC6FVwQMzfhCU7FHbVXaac0AgRco1v+e2dTEovCSLpcAGnaIkKMArQsiHyda/UeO/tkQloJYqYDswvTZrRF0GNB5DxYbRbYXt8ak8a9HYfokX+BgTDK9STka1FNLxdu+4ryzKYMBuCQi/lY4hHbucdDr4lC7o4=
  file:
    - 'html-void-elements.js'
    - 'html-void-elements.min.js'
  on:
    tags: true
